### ISSUE TITLE
Pictures don't show, Warning: JFolder Path is not a folder

### ISSUE THREAD

**Issue by fstoltz** [AlexRed/ozio#2]
Hi,

when I enter the Ozio Gallery Menu Item, this warning is on top.

"Warning
JFolder: :files: Path is not a folder. Path: /home/kadagaya/public_html/media/com_oziogallery3/views/map/img/markers/icons"

Anyone got a clue on how to solve it?

Link to site not showing pictures:
http://kadagaya.org/index.php/en/photo-gallery

It's been working flawless for quite some time.

Cheers & Thanks

**Comment by AlexRed** [comment]
Hello fstoltz,
what's Ozio Gallery menu type ?
"Map of photos" ?
like: https://www.opensourcesolutions.es/en/fuerteventura-photo-map.html

**Comment by fstoltz** [comment]
Thank you for the quick response @AlexRed ,

At the moment it is set to Menu Item Type: `Skin Nano`

and link is set to: `index.php?option=com_oziogallery3&view=nano`

**Comment by AlexRed** [comment]
Please check the params "Markers icon" in the Skin Nano menu item option, try to set "Use default"

**Comment by fstoltz** [comment]
It's set to "Use Default" as shown below.
![capture](https://cloud.githubusercontent.com/assets/22579564/20987812/5cab956c-bcce-11e6-8695-ce5de0e40d44.PNG)

I notice that when hovering "Components", it says "Ozio Gallery 4". But this warning I get is specifying a path with Ozio Gallery 3 in it. (I don't know if this warning has to do with the fact that pictures aren't showing up, just something I noticed)

"Warning
JFolder: :files: Path is not a folder. Path: /home/kadagaya/public_html/media/com_**oziogallery3**/views/map/img/markers/icons"

I appreciate the help.

**Comment by AlexRed** [comment]
The components name is ok.
Under the "Markers icon" params can you see the icon image?

Please send me the ID number of your Joomla Ozio Gallery menu item.

The problem is the browser can't find the Ozio Gallery files in your site server, like: http://kadagaya.org/media/com_oziogallery3/views/nano/js/jquery.nanogallery.js

try to reinstall the 4.7.0 Ozio Gallery version, and check via FTP the file is in the folder.

**Comment by fstoltz** [comment]
I don't think so, this is how it looks:
![ozio](https://cloud.githubusercontent.com/assets/22579564/21004616/998bdde4-bd31-11e6-8789-5e41615637b9.PNG)

The ID of the Menu Item is `111`

Alright, I see. I entered the host and was checking, and inside `media/com_oziogallery3`, it is completely empty. 

Ok, I guess that means uninstalling the Ozio extension, just to make sure, I should uninstall all of these, and then just install Ozio from scratch?
![oziotroubleshooting](https://cloud.githubusercontent.com/assets/22579564/21004680/e83acb44-bd31-11e6-8bf5-95bfd70d63d0.PNG)

**Comment by AlexRed** [comment]
no, do not unistall. Just install the Ozio Gallery 4.7.0

**Comment by fstoltz** [comment]
Went to `Extensions > Manage > Update > Find Updates`. And then the `Ozio Gallery 4.7.0` showed up.

It did its thing, and works like a charm now!

Turned out to be a very simple solution, but **thanks Alessandro** for the help! Time to go and leave a review for Ozio Gallery.

English Gallery: [http://kadagaya.org/index.php/en/photo-gallery](http://kadagaya.org/index.php/en/photo-gallery)

Spanish Gallery: [http://kadagaya.org/index.php/es/galeria](http://kadagaya.org/index.php/es/galeria)

**Comment by AlexRed** [comment]
Fantastic!
Thansk for the review, it is more important for us  :+1:
