### ISSUE TITLE
nanoGALLERY: Could not retrieve Picasa/Google+ data... [nanoGallery]

### ISSUE THREAD

**Issue by scw1937** [AlexRed/ozio#3]
Hi there,

There seems to be a problem loading new albums from Google Photos using Skin Nano.

If I choose no albums in Album List, in order to show them all, it only shows old public (profile) photos. I am able to choose a new album in Album List, but then a message shows up on the web page:
`nanoGALLERY: Could not retrieve Picasa/Google+ data... [nanoGallery]`

If I choose a new album and an old album, then the old one loads and no error message shows up. So, may be the message only shows up when no album could be loaded.

Could you reproduce this error? Please let me know whether you need more info.

Ozio Gallery 4.8.0
Joomla! 3.6.5

**Comment by AlexRed** [comment]
Hello scw1937,
please read:  https://plus.google.com/+AlessandroRossiAlexRed/posts/L69xH97FdnF

**Comment by scw1937** [comment]
Hi Alex,

Thank you for your fast response.

At first, the new albums did not load while I certainly did select them in the Album List. The next day (today) they are visible. Could be Google or me forgetting to clear cache. Anyway, in the end it does work and I'm really happy about it. Thanks to you a local football club is able to share sports photos in a nice way.

Keep up the good work!

**Comment by AlexRed** [comment]
Remember, ....if you use Ozio Gallery, please post a rating and a review (in english) at the Joomla! Extensions Directory (JED) http://extensions.joomla.org/extensions/extension/photos-a-images/galleries/ozio-gallery#reviews   
Thanks for your help.
