### ISSUE TITLE
Could not retrieve Picasa/Google+ data (jQuery): parsererror, SyntaxError: Unexpected token N in JSON at position 1

### ISSUE THREAD

**Issue by stefanw79** [AlexRed/ozio#5]
Hi!

I use OzioGallery since some years, but since some days I always get the error "Could not retrieve Picasa/Google+ data (jQuery): parsererror, SyntaxError: Unexpected token N in JSON at position 1", when I try to receive the album list.
Also at existing Menu-Entries.

I worked in September.
Authentication is Ok.

OzioGallery 5.03 on Joomla! 3.9.14.

I´ve also tried to uninstall and install again -> Still the same error.

-
Stefan

**Comment by AlexRed** [comment]
Hello stefanw79,
be sure no empty album on Google Photos.
And try to create a new credential in the Google API console and autenticate it in the Ozio Gallery control panel.

**Comment by stefanw79** [comment]
Hi!

Thanks for the fast reply.

> And try to create a new credential in the Google API console and autenticate it in the Ozio Gallery control panel.

This was the problem. I´ve dropped the credentials at Joomla and created a new OAuth-ID at Google.
Now I works.

Many thanks!

-Stefan
